services:
  - type: web
    name: newcollege-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: GEMINI_KEYS
        sync: false
      - key: ADMIN_SECRET_KEY
        sync: false
      - key: FLASK_ENV
        value: production
